apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: default
  labels:
    app: opentelemetry-collector
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      k8sattributes:
      filter:
        logs:
          include:
            match_type: regexp
            expressions:
            - "Sample log message"
      resource:
        attributes:
        - key: custom_attribute
          value: "custom_value"
          action: upsert
      resourcedetection:
        detectors: [system, gce, k8s]

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [k8sattributes, filter, resource, resourcedetection]
          exporters: [logging]
