apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-opentelemetry-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-opentelemetry-logs
  template:
    metadata:
      labels:
        app: demo-opentelemetry-logs
    spec:
      containers:
      - name: demo-opentelemetry-logs
        image: <your-docker-hub-username>/demo-opentelemetry-logs:latest
        ports:
        - containerPort: 8080
